# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# This package was autogenerated by scripts/generate-astal-ebuilds.py.
# Prefer to edit scripts/generate-astal-ebuilds.py over this ebuild directly.

EAPI=8

DESCRIPTION="Meta package for the Astal library collection"
HOMEPAGE="https://github.com/Aylur/astal"

LICENSE="metapackage"
SLOT="0"
KEYWORDS="~amd64"
IUSE="apps auth battery bluetooth brightness cava gjs greetd +gtk3 gtk4 hyprland mpris network notifd powerprofiles river tray wireplumber"
REQUIRED_USE="gjs? ( || ( gtk3 gtk4 ) )"

RDEPEND="
	gui-libs/astal-io
	apps? ( gui-libs/astal-apps )
	auth? ( gui-libs/astal-auth )
	battery? ( gui-libs/astal-battery )
	bluetooth? ( gui-libs/astal-bluetooth )
	brightness? ( gui-libs/astal-brightness )
	cava? ( gui-libs/astal-cava )
	gjs? ( gui-libs/astal-gjs[gtk3=,gtk4=] )
	greetd? ( gui-libs/astal-greetd )
	gtk3? ( gui-libs/astal-gtk3 )
	gtk4? ( gui-libs/astal-gtk4 )
	hyprland? ( gui-libs/astal-hyprland )
	mpris? ( gui-libs/astal-mpris )
	network? ( gui-libs/astal-network )
	notifd? ( gui-libs/astal-notifd )
	powerprofiles? ( gui-libs/astal-powerprofiles )
	river? ( gui-libs/astal-river )
	tray? ( gui-libs/astal-tray )
	wireplumber? ( gui-libs/astal-wireplumber )
"
