# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# This package was autogenerated by scripts/generate-astal-ebuilds.py.
# Do not edit directly.

EAPI=8

PYTHON_COMPAT=( python3_{11..15} )
VALA_USE_DEPEND="valadoc vapigen"
inherit meson python-any-r1 vala gnome2-utils

DESCRIPTION="Notification daemon library and command-line tool"
HOMEPAGE="https://github.com/Aylur/astal"
REVISION="9dac92f20e6c89b9373bbb238c49b1cb115724db"
SRC_URI="https://github.com/Aylur/astal/archive/${REVISION}.tar.gz -> astal-${REVISION}.tar.gz"
S="${WORKDIR}/astal-${REVISION}"
EMESON_SOURCE="${S}/lib/notifd"

LICENSE="LGPL-2.1"
SLOT="0"
KEYWORDS="~amd64"

RDEPEND="
	dev-libs/glib:2
	dev-libs/json-glib
	gui-libs/astal-quarrel
	x11-libs/gdk-pixbuf:2
"
DEPEND="${RDEPEND}"
BDEPEND="
	${PYTHON_DEPS}
	dev-build/meson
	$(vala_depend)
	dev-libs/gobject-introspection
"
src_configure() {
	vala_setup
	meson_src_configure
}

pkg_postinst() {
	gnome2_schemas_update
}

pkg_postrm() {
	gnome2_schemas_update
}
