# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# This package was autogenerated by scripts/generate-astal-ebuilds.py.
# Do not edit directly.

EAPI=8

inherit meson

DESCRIPTION="GJS bindings for Astal"
HOMEPAGE="https://github.com/Aylur/astal"
REVISION="9dac92f20e6c89b9373bbb238c49b1cb115724db"
SRC_URI="https://github.com/Aylur/astal/archive/${REVISION}.tar.gz -> astal-${REVISION}.tar.gz"
S="${WORKDIR}/astal-${REVISION}"
EMESON_SOURCE="${S}/lang/gjs"

LICENSE="LGPL-2.1"
SLOT="0"
KEYWORDS="~amd64"
IUSE="+gtk3 gtk4"
REQUIRED_USE="|| ( gtk3 gtk4 )"

RDEPEND="
	dev-libs/gjs
	gui-libs/astal-io
	gtk3? ( gui-libs/astal-gtk3 )
	gtk4? ( gui-libs/astal-gtk4 )
"
DEPEND="${RDEPEND}"
BDEPEND="
	dev-build/meson
"
